### ISSUE TITLE
Only shows "Quit" option in Linux

### ISSUE THREAD

**Issue by hrqmonteiro** [mikaelkristiansson/gitbar#22]
![Screenshot from 2023-05-16 19-35-41](https://github.com/mikaelkristiansson/gitbar/assets/17055027/10a1cb22-e6ac-4d2e-99c8-ba7246f9fb2a)

How to use this? .AppImage version on Fedora.

**Comment by mikaelkristiansson** [comment]
I still have not figured out a way to run this on Linux, and I dont have any device to try it out either. Feel free to come with suggestions. :)

**Comment by hrqmonteiro** [comment]
> I still have not figured out a way to run this on Linux, and I dont have any device to try it out either. Feel free to come with suggestions. :)

Why did you release it for Linux, then?
...
